### ISSUE TITLE
VsOpenIn does not load after update in VS2013

### ISSUE THREAD

**Issue by MartinL0815** [jquintus/VsOpenIn#2]
Today I updated VsOpenIn to the newest version - notificated for update by VS2013.

After restarting the package didn't load and the activity log listed the following:
1. Begin package load [VsOpenInPackage] {E869A176-EBBA-4477-AB62-38F1B3D24C55}  VisualStudio 2015/08/10 08:46:47.920 
2. ERROR CreateInstance failed for package [VsOpenInPackage] {E869A176-EBBA-4477-AB62-38F1B3D24C55} **80070002** VisualStudio 2015/08/10 08:46:47.920 
3. ERROR End package load [VsOpenInPackage] {E869A176-EBBA-4477-AB62-38F1B3D24C55} 80004005 - E_FAIL VisualStudio 2015/08/10 08:46:47.920 

Any chance for a quick fix?

**Comment by jquintus** [comment]
I'll revert the update this afternoon. I'm not sure why it would cause any
problems

**Comment by MartinL0815** [comment]
What have been the latest changes? VS2015 support?
I ask, because I wasn't really able to find the changes history somewhere.

**Comment by MartinL0815** [comment]
Ok - sorry, found the change ... VS2015.

**Comment by jquintus** [comment]
All I did was edit the manifest and added VS2015 to the list of supported
editions.

**Comment by jquintus** [comment]
I don't have a copy of the previous build on my computer and I don't have the required software installed to rebuild it.  I'll take care of this when I get home.  I should have this fixed in about 6 hours.  

Sorry for the delay there.

**Comment by jquintus** [comment]
I've recompiled and published an update.  Please let me know if this fixes the problem.

**Comment by jquintus** [comment]
reopening until I hear back from Martin.

**Comment by jquintus** [comment]
If the version on VisualStudioGallery doesn't work, would you mind trying this version:  https://ci.appveyor.com/api/buildjobs/sl4ygq4hpdwqgx0w/artifacts/VsOpenIn/VsOpenIn/bin/Release/VsOpenIn.vsix 

The issue may just be that my dev laptop is no longer configured correctly, so hopefully using the build server helps.

**Comment by MartinL0815** [comment]
Sorry, the version from the Visual Studio Gallery didn't fix it, so I had to use the version, including a forced uninstall, you provided in your last comment.
But now VS2013 ist starting without complaining about VsOpenIn anymore!

**Comment by jquintus** [comment]
So the last version worked for you? That's great. I'll publish that one
once I get to work.  I'll let you know when it is available.

Thanks for the help.

**Comment by jquintus** [comment]
The latest version is back in the gallery.  @MartinL0815, you should be able to install from there again.  Thanks again for reporting the error and testing my fix.
